#!/bin/sh -ef
# Display a package's dependencies

pkg=${1:-"${PWD##*/}"}

gozpak list "$pkg" >/dev/null || {
    printf 'usage: gozpak-depends [pkg]\n' >&2
    exit 1
}

while read -r dep mak || [ "$dep" ]; do
    printf '%s%s\n' "$dep" "${mak:+ "$mak"}"
done 2>/dev/null < "$GOZPAK_ROOT/var/db/gozpak/installed/$pkg/depends" 
